compressionLevel: mixed

defaultSemverRangePrefix: ""

enableGlobalCache: false

nodeLinker: pnp

npmAuthToken: "${NODE_AUTH_TOKEN:-}"

supportedArchitectures:
  cpu:
    - x64
  os:
    - linux
    - win32
  libc:
    - glibc

yarnPath: .yarn/releases/yarn-4.6.0.cjs
